dbt_snowflake_poc:
  target: dev                                  # default; devy nadpisują w Workspace
  outputs:

    # ---------- PERSONAL (per dev) ----------
    personal_jakub:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: DBT_POC_DEV_JAKUB
      database: PERSONAL_DEVELOPMENT
      schema: jakub_wojciechowski
      warehouse: WH_DBT_POC_DEV
      threads: 8

    personal_klaudia:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: DBT_POC_DEV_KLAUDIA_CIOCHON
      database: PERSONAL_DEVELOPMENT
      schema: KLAUDIA_CIOCHON
      warehouse: WH_DBT_POC_DEV
      threads: 8

    personal_patryk:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: DBT_POC_DEV_PATRYK_KRAJEWSKI
      database: PERSONAL_DEVELOPMENT
      schema: PATRYK_KRAJEWSKI
      warehouse: WH_DBT_POC_DEV
      threads: 8
      
    # ---------- DEV (TVN AD_SALES, shared) ----------
    dev:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: DBT_TVN_DEV                        # rola pisarska tylko na DB_TVN_AD_SALES_*_DEV
      database: DB_TVN_AD_SALES_LOAD_STAGE_DEV # fallback; modele nadpisują przez +database
      schema: SCH_STAGE                        # fallback; modele nadpisują przez +schema
      warehouse: WH_DBT_POC_DEV
      threads: 8

    # ---------- PRD (TVN AD_SALES, produkcja) ----------
    prd:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: DBT_TVN_PRD                        # rola pisarska tylko na DB_TVN_AD_SALES_*_PRD
      database: DB_TVN_AD_SALES_LOAD_STAGE_PRD
      schema: SCH_STAGE
      warehouse: WH_DBT_POC_PRD
      threads: 8
